-- Migration number: 0001
CREATE TABLE IF NOT EXISTS athletes (
  id INTEGER PRIMARY KEY,           -- Strava athlete id
  firstname TEXT,
  access_token TEXT NOT NULL,       -- AES-GCM encrypted
  refresh_token TEXT NOT NULL,      -- AES-GCM encrypted
  expires_at INTEGER NOT NULL,      -- epoch seconds
  scope TEXT,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id_hash TEXT PRIMARY KEY,         -- SHA-256 of the session token
  athlete_id INTEGER NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  created_at INTEGER NOT NULL
);

-- OAuth <-> PWA bridge: the state generated by the PWA is used to claim the session,
-- without relying on a cookie (see the iOS in-app browser in standalone mode)
CREATE TABLE IF NOT EXISTS oauth_states (
  state TEXT PRIMARY KEY,
  session_token TEXT,
  created_at INTEGER NOT NULL
);
