-- Migration number: 0005
-- Personal card templates, per athlete (see worker/index.ts /templates routes).
CREATE TABLE IF NOT EXISTS templates (
  provider TEXT NOT NULL,
  athlete_id INTEGER NOT NULL,
  id TEXT NOT NULL,                 -- random id generated by the worker
  name TEXT NOT NULL,
  options TEXT NOT NULL,            -- JSON (TemplateOptions, see src/lib/templates.ts)
  created_at INTEGER NOT NULL,
  PRIMARY KEY (provider, athlete_id, id)
);
